// Full FPGA design: core + peripherals + top, plus the design testbench.
rtl/core/Adder.sv
rtl/core/ALU.sv
rtl/core/BranchComparator.sv
rtl/core/Controller.sv
rtl/core/ControllerA.sv
rtl/core/ControllerB.sv
rtl/core/ControlStatusReg.sv
rtl/core/DataMemory.sv
rtl/core/Datapath.sv
rtl/core/FSF_unit.sv
rtl/core/InstructionMem.sv
rtl/core/LoadStoreUnit.sv
rtl/core/Mux_2x1.sv
rtl/core/Mux2x1.sv
rtl/core/Mux_3x1.sv
rtl/core/Mux_4x1.sv
rtl/core/ProgramCounter.sv
rtl/core/RegisterFile.sv
rtl/core/SignExtender.sv
rtl/core/TimerIntrpt.sv
rtl/core/regDEMW.sv
rtl/core/regFDE.sv
rtl/peripherals/BaudRateGen.sv
rtl/peripherals/BitCounter.sv
rtl/peripherals/ShiftReg.sv
rtl/peripherals/UART.sv
rtl/peripherals/uartController.sv
rtl/peripherals/anodeSelect.sv
rtl/peripherals/bcd.sv
rtl/peripherals/clockDivider.sv
rtl/peripherals/refreshCounter.sv
rtl/peripherals/sevenSeg.sv
rtl/top/RISCV.sv
verif/tb/tb_RISCV.sv
